[package]
name = "implot-sys-bindgen"
version = "0.1.0"
authors = ["Sandro Merkli"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.53.1"
imgui-sys = { version = "0.5.0" }
imgui = { version = "0.5.0" }
