[package]
name = "implot-wgpu-demo"
version = "0.1.0"
authors = ["Benedikt Mandelkow <benedikt.mandelkow@rwth-aachen.de>", "imgui-wgpu contributors"]
edition = "2018"

[dependencies]
implot = { path = "../../" }

imgui = "^0.5.0"

# imgui backend for drawing using wgpu
imgui-wgpu = { git = "https://github.com/benmkw/imgui-wgpu-rs/", branch = "api", features = ["simple_api_unstable"] }

examples-shared = { path = "../examples-shared" }
