name: Tests


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jwsi/submodule-checkout@v1
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run idiomatic bindings tests 
      run: cargo test --verbose
    - name: Run FFI tests 
      run: cd implot-sys/ && cargo test --verbose
    - name: Build glium demo
      run: cd implot-examples/implot-glium-demo && cargo build
    - name: Build wgpu demo
      run: cd implot-examples/implot-wgpu-demo && cargo build
